### ISSUE TITLE
string * bool is not in the Skylark spec

### ISSUE THREAD

**Issue by alandonovan** [google/starlark-rust#10]
I just noticed the string*bool operator:
https://github.com/google/starlark-rust/blob/a21a387078013a2b9d6524b6f651a2c337ea9c20/src/values/string.rs#L168
This isn't in the Skylark spec or Java or Go impls.

I wonder: what set of features were you working toward?

**Comment by damienmg** [comment]
I used your spec and the python behavior to guide me and for string * bool, this was because the spec wasn't clear so I copied the python behavior. My goal was to match at least the behavior of the Java version.

**Comment by alandonovan** [comment]
If the spec isn't clear, please report a bug against it.  But I'm not sure why you think it's ambiguous on this point: string*number and number*string are allowed, but there is no mention of string*bool, and bool is not a number.  The Go and Java implementations agree on this. Iit would be a shame for the first implementation created with the benefit of a written specification not to comply with it!

**Comment by damienmg** [comment]
https://github.com/google/skylark/blob/a0e5de7e63b47e716cca7226662a4c95d47bf873/doc/spec.md#strings is not even specifying `string * number`. I cannot find it in the current spec either.

Anyway, I am preparing a fix for it and I'll open a corresponding bug to fix the spec.

**Comment by alandonovan** [comment]
It was covered by "sequence * number" in the Arithmetic Operations section (https://github.com/google/skylark/blob/a0e5de7e63b47e716cca7226662a4c95d47bf873/doc/spec.md#arithmetic-operations) though it should be updated because strings are no longer considered sequences.

**Comment by damienmg** [comment]
Thanks I commented on bazelbuild/starlark#9 improvements that might have helped me avoid the mistake and #11 is fixing the issue.
