### ISSUE TITLE
Using starlark_module! requires wide-ranging imports

### ISSUE THREAD

**Issue by antifuchs** [google/starlark-rust#12]
I just tried using starlark-rust for a rewrite/extension of an old side-project of mine, and I've got an experience report in progress: Using the `starlark_module!` macro requires somewhat unergonomic boilerplate code.

Instead of the following 2015 edition rust (for 2018 edition rust, you have to pull in the macros explicitly, which is a bit more unwieldy since you also have to import all the macros that the `starlark_module` block expands into):

``` rust
#[macro_use]
extern crate starlark;
use starlark::values::Value;

// all of the below things are required to expand the macro correctly 
// (I kept adding them until rustc stopped screaming at me):
use starlark::environment::Environment;
use starlark::values::function;
use starlark::values::ValueResult;

starlark_module!{
    ohai =>
        hi(_a) {
            Ok(Value::from(None))
        }
}
```

I believe this could be avoided by making the macro expansion use [the `$crate` variable](https://doc.rust-lang.org/1.5.0/book/macros.html#the-variable-crate) (weirdly enough not documented in newer editions of the rust book) to canonize names exported by starlark-rust. I'm happy to draft up a PR, it would be a straightforward search&replace job.

**Comment by damienmg** [comment]
I'd love to as long as we can keep the crate working with the stable
channel. If we cannot, I need to think more.

**Comment by antifuchs** [comment]
Ah, I'm pretty sure that should work - I think that variable has been in rust since 1.5. I'll try now (:
