### ISSUE TITLE
Coroutine/Generator Support

### ISSUE THREAD

**Issue by stuhood** [google/starlark-rust#14]
Hello! Thank you for creating this project: it's a wonderful contribution to both the rust and starlark communities.

I've started work on a series of 4-5 (relatively small) PRs that would add initial support for Python's `yield` syntax for coroutines/generators. Our (in http://github.com/pantsbuild/pants/) usecase only requires consuming the coroutines from the host language, so those PRs would not add builtins/stdlib-fns for resuming generators from starlark*, and would instead assume that the host language would be directly aware of a `Generator` `TypedValue`, and would resume evaluation that way.

Would the committer(s) be willing to accept these patches? The end-user visible differences could be very limited: it should be straightforward to disable the `yield` statement via an option if need be.

\* _which would require a bit of spec work, since starlark does-not/should-not support exceptions, and Python uses `StopIteration` in its interface._

**Comment by damienmg** [comment]
So having talk with @laurentlb on another issue around experimental feature this sounds good to me, just make sure we flag it behind a feature

**Comment by laurentlb** [comment]
Yes, it's okay to do experimentation behind a flag.

However, if the goal is to have some compatibility with Bazel (macros or rules), you should probably avoid introducing this kind of divergence (focus on the core, before considering any non-standard extension).

**Comment by alandonovan** [comment]
Please don't introduce (even experimental) support for generators until all the core features are correctly implemented. I couldn't find any evidence that skylark-rust detects attempts to mutate a list or dict while iterators are active, and this is almost certain to have subtle interactions with generators.

Fortunately there is a good spec and a test suite from which you can borrow liberally to ensure that this implementation of Starlark is fully compatible with the other two. If this was my project, that would be my first priority.

**Comment by damienmg** [comment]
> Please don't introduce (even experimental) support for generators until all the core features are correctly implemented. I couldn't find any evidence that skylark-rust detects attempts to detect mutation of a list or dict while iterators are active, and this is almost certain to have subtle interactions with generators.

That's issue #3 

> 
> Fortunately there is a good spec and a test suite from which you can borrow liberally to ensure that this implementation of Starlark is fully compatible with the other two. If this was my project, that would be my first priority.

Which one? Because I used all the integration tests from both the Java version and the go version at the time. Each of them are specific to their own implementation and I opened https://github.com/bazelbuild/starlark/issues/10 to address that.

**Comment by stuhood** [comment]
Thanks folks. Will pick this back up this weekend.

**Comment by stuhood** [comment]
I haven't gotten a lot of time to work on this, and I'm not sure when I'll next be able to pick it up. Have pushed it over here: https://github.com/google/starlark-rust/compare/master...stuhood:stuhood/generators

**Comment by damienmg** [comment]
No worries Stu, thanks for sharing the code so far.
