### ISSUE TITLE
Add some examples of crate usage

### ISSUE THREAD

**Issue by wickedchicken** [google/starlark-rust#187]
Hi, thanks a ton for this project! I'm relatively new to Rust and found integrating `starlark-rust` into a program a bit intimidating. Would you be open to adding some examples to the documentation? They could go in the `README.md`, an `examples` directory, or the `rustdoc` comments themselves. I ended up reading code in the [starlark-repl](https://github.com/google/starlark-rust/blob/master/starlark-repl/) directory to get familiar with how to use it, but it's a bit more complicated to parse than I had hoped. The specific information I was hoping to see was how `codemap` and `starlark::stdlib::global_environment` were meant to be used with `eval`, and how to use a `Value` returned from `eval`.

I made some sample code for myself, but it might be a bit too long for the `README.md` (it's also not directly compilable being outside a function, but I think that would make it even longer):

```rust
extern crate codemap;
extern crate codemap_diagnostic;
extern crate starlark;

use std::sync::{Arc, Mutex};

use codemap_diagnostic::{ColorConfig, Emitter};
use starlark::eval::simple::eval;
use starlark::stdlib::global_environment;

let starlark_input = "str([2 * x for x in range(5)])";

let global_env = global_environment();
global_env.freeze();
let mut env = global_env.child("shell_loop");
let map = Arc::new(Mutex::new(codemap::CodeMap::new()));

let res = match eval(&map, "string input", &starlark_input, true, &mut env) {
    Err(diag) => {
        let cloned_map = Arc::clone(&map);
        let unlocked_map = cloned_map.lock().unwrap();
        Emitter::stderr(ColorConfig::Always, Some(&unlocked_map)).emit(&[diag]);
        panic!("Error interpreting code '{}'", starlark_input);
    },
    Ok(res) => match res.get_type() {
        "string" => res.to_str(),
        _ => panic!(
            "Error interpreting code '{}': result must be string! (was {})",
            starlark_input,
            res.get_type()
        )
    }
};
```

I've signed the CLA so feel free to use or modify it if it seems useful. Thanks again, and looking forward to hearing your response!

**Comment by damienmg** [comment]
Hi that looks like a good example to me. Would you mind sending a PR to add this either in a rustdoc somewhere or directly in an starlark-examples crate in this repository? (I don't think I can take code from someone even who has sign the CLA, because it would remove trace of authorship).

**Comment by wickedchicken** [comment]
Awesome, thanks!
