### ISSUE TITLE
Switch starlark-repl to structopt?

### ISSUE THREAD

**Issue by wickedchicken** [google/starlark-rust#189]
The [starlark-repl](https://github.com/google/starlark-rust/blob/c4349ab634a2e13fb602bb3442ac96b72e6a5270/starlark-repl/) binary uses custom [`getopts` parsing](https://github.com/google/starlark-rust/blob/c4349ab634a2e13fb602bb3442ac96b72e6a5270/starlark-repl/bin/starlark-rust.rs#L19) to parse its command-line arguments. This requires a lot of hand-written boilerplate, such as manually printing out help. I'd like to convert it to use [structopt](https://github.com/TeXitoi/structopt), where command-line arguments are defined in a structured way to reduce boilerplate. Before I do that, I wanted to see what the maintainers think. Would this change be well-received? Thanks!

**Comment by illicitonion** [comment]
Personally I love structopt and would welcome the change! Not sure how @damienmg feels :)

**Comment by damienmg** [comment]
I am a huge fan of structopt and since this dependency won't be added to
the main crate I would welcome such a change!

**Comment by wickedchicken** [comment]
Awesome, I'll start cooking up a PR then.
