### ISSUE TITLE
Accessing local variables in a Starlark module.

### ISSUE THREAD

**Issue by iwasaki-kenta** [google/starlark-rust#191]
Is there any way to access local variables declared outside the `starlark_module!` macro, or to allow for closures to be provided as a `NativeFunction`?

Otherwise, how could I import external functions or variables into a Starlark module?

**Comment by damienmg** [comment]
Hi, I am not sure I understand what you want to do.

Why do you want closure to be a NativeFunction? Do you want to import other starlark file in a starlark file as a module? The usual way to do that is to import a struct with each closure being an argument of the structure.

**Comment by iwasaki-kenta** [comment]
> Hi, I am not sure I understand what you want to do.
> 
> Why do you want closure to be a NativeFunction? Do you want to import other starlark file in a starlark file as a module? The usual way to do that is to import a struct with each closure being an argument of the structure.

I would like to for example define a:

```rust
let notifications: Vec<String> = Vec::new();
```

In a starlark_module!(), I would like to then append to `notifications`.

```rust
starlark_module!( module => {
    fn notify(domain) {
        notifications.push(domain.to_str());
    }
}
```

However, this wouldn't work as I would not be able to access the `notifications` var. Is there any way I can re-architect this such that I can import a `notify` function into a Starlark environment that would interact with local vars?

**Comment by damienmg** [comment]
Notifications should be attached to an object and you can add the object to the environment (cf [NoneType](https://github.com/google/starlark-rust/blob/master/starlark/src/values/none.rs) and [its insertion in the global environment](https://github.com/google/starlark-rust/blob/master/starlark/src/stdlib/mod.rs#L953))

Notify would then be notifications.notify if notifications if your dedicated type.

Would that work for you?

**Comment by iwasaki-kenta** [comment]
> Notifications should be attached to an object and you can add the object to the environment (cf [NoneType](https://github.com/google/starlark-rust/blob/master/starlark/src/values/none.rs) and [its insertion in the global environment](https://github.com/google/starlark-rust/blob/master/starlark/src/stdlib/mod.rs#L953))
> 
> Notify would then be notifications.notify if notifications if your dedicated type.
> 
> Would that work for you?

Works just fine, thank you!
