### ISSUE TITLE
starlark-rust is difficult to embed because monolithic crate pulls in heavy dependencies

### ISSUE THREAD

**Issue by jmillikin** [google/starlark-rust#23]
The `starlark` crate contains not only the core Starlark parser and evaluator, but also the interactive REPL with its huge dependency tree. This sharply limits the utility of starlark-rust as an embedded library.

Following the example of https://github.com/rust-lang-nursery/futures-rs, can the current monolithic crate be split up? Keeping it in the same repo is fine, I just want separate compilation units.

**Comment by damienmg** [comment]
Hi John,

I am very much for it.
