### ISSUE TITLE
Make codemap/codemap-diagnostic optional dependencies.

### ISSUE THREAD

**Issue by damienmg** [google/starlark-rust#26]
As a follow-up of #23, I'll make the codemap dependency optional also because it might not necessarly make sense to use it depending on your application.

**Comment by stepancheg** [comment]
FYI untangled dependencies won't be an issue as soon as Rust RFC 1977 implemented (`codemap` could be marked private dependency), and as far as I see, this RFC is being implemented now.

**Comment by anp** [comment]
Would there be any interest in supporting https://docs.rs/annotate-snippets? It looks to be pretty actively developed.
