### ISSUE TITLE
Consider releasing a new version

### ISSUE THREAD

**Issue by ch2ray** [google/starlark-rust#263]
Hi and thanks for the awesome crate!

It's been more than a year since the last release on crates.io (2018). Would you like to cut a 3.0 release with all the new changes?

**Comment by damienmg** [comment]
Hi sorry, I was in a lot and could not contribute to open-source for a long time. I will cut a new release now.

**Comment by damienmg** [comment]
Done. I also sent an invite to @stepancheg who for some reason was not admin on the crates.
