### ISSUE TITLE
x[0]=x produces a "recursive data structure" error

### ISSUE THREAD

**Issue by alandonovan** [google/starlark-rust#267]
(I've been poking around the interpreter to understand Rust.)

The Starlark spec permits recursive data structures (and they do occur in practice), but the Rust implementation causes cycle-forming operations to fail dynamically. For example:
```
$ cat a.star 

x = [0]
d = dict(a=x)
y = struct(f=d)

x[0] = y

$ cargo run a.star
error[CV14]: This operation create a recursive data structure. Recursive datastructure are disallowed because infinite loops are disallowed in Starlark.
 --> a.star:6:1
  |
6 | x[0] = y
  | ^^^^ Unsupported recursive data structure
```

The implementation of this assignment check requires traversing the complete object graph of x to see if it contains a references to x itself. This is asymptotically expensive, as it requires pulling the complete object graph of x in from main memory. There's no efficient general way to implement this check, so it doesn't seem like a good language feature, even though it's a neat idea and solves other problems, such as recursive functions (print, hash, equals) getting stuck.

I suspect the real reason for this check is that Rust has no garbage collector. Rather than implement one, you used Rc reference counts to manage the lifetimes of Starlark values, but a known limitation of plain reference counting is that it fails to collect cycles, so you outlawed cycles, contra the spec. (Am I right?)

To support cycles, Starlark-Rust will need a partial tracing garbage collector; take a look at Retracer ("Concurrent Cycle Collection in Reference Counted System", Bacon & Rajan, ECOOP 2001; Googlers: GCL contains a C++ implementation) or you could do what CPython does. You already implemented tracing (is_descendant). In effect, the Rust owner of all values would be the GC.

**Comment by damienmg** [comment]
> I suspect the real reason for this check is that Rust has no garbage collector. Rather than implement one, you used Rc reference counts to manage the lifetimes of Starlark values, but a known limitation of plain reference counting is that it fails to collect cycles, so you outlawed cycles, contra the spec. (Am I right?)

You are correct. It was a choice made on the first version of the implementation, and IIRC at the time the Java Starlark implentation was disallowing recursive structure.

@stepancheg was working on a GC implementation, which is the way I would like to go in the long term.
