### ISSUE TITLE
How to implement rust-native functions outside of starlark crate?

### ISSUE THREAD

**Issue by illicitonion** [google/starlark-rust#269]
I was thinking of implementing some starlark-exposed functions in Rust (outside of the `starlark` crate itself), but I noticed that `FunctionSignature::new` is `pub(crate)`, and much of the machinery surrounding `NativeFunction` is `doc(hidden)`. Is there another way to implement functions and exposing them to an `Environment`? If not, how would folks feel about opening up `FunctionSignature::new`? I think I'm fine with leaving them undoc'd (they're slightly weird APIs, and I'm not sure we think they're stable extension points at the moment), but I'm curious as to why we ended up with them restricted.

/cc @stepancheg @damienmg

**Comment by damienmg** [comment]
Hi Daniel,

Using the `starlark_module!` macro, you can define your own function in Rust, e.g.:

https://github.com/google/starlark-rust/blob/master/starlark/src/stdlib/mod.rs#L51

**Comment by damienmg** [comment]
And the documentation: https://docs.rs/starlark/0.3.0/starlark/macro.starlark_module.html :)
