### ISSUE TITLE
Debug print statement in starlark::environment::TypeValues::get_type_value()

### ISSUE THREAD

**Issue by indygreg** [google/starlark-rust#270]
There is a `println!("{:?}", self)` at https://github.com/google/starlark-rust/commit/57aa68778349cd62436ef96e640b6be2d78c02a6#diff-3aaa36185590979cba661351eaa38456R277 that doesn't belong.

I'm blocked on releasing https://github.com/indygreg/PyOxidizer 0.8 to crates.io (due to published crate dependency requirement) due to this bug because I must call this function :(

**Comment by indygreg** [comment]
Thank you for fixing this! I probably should have created a PR myself to save you the work. (I file bug reports instinctively instead of jumping in for the fix sometimes. Bad habit from a prior job...)

**Comment by indygreg** [comment]
Is there an ETA on publishing a new crate version with this fix? Due to crate.io's requirement that all crate dependencies must be published on crates.io, I'm unable to publish a crate depending on this fix.

I don't want to pressure you into releasing and I'm likely a few days from a release on my own. If there's anything I can do to help with the release process, let me know.

**Comment by damienmg** [comment]
This should be done now.

**Comment by indygreg** [comment]
Thank you so much! The new release is plugged in and is working without issue.
