### ISSUE TITLE
Some Error Codes Collide

### ISSUE THREAD

**Issue by Mythra** [google/starlark-rust#277]
While looking into parsing errors inside of my crate to show slightly nicer error messages for my application specifically I've noticed that there seem to be several error codes that collide. Specifically the module error codes export `CE02`, and `CE03` for the cause: `CANNOT_IMPORT_ERROR_CODE`, and `BORROW_ERROR_CODE`:

https://github.com/google/starlark-rust/blob/2002bb10de0773b346523efe902aeea86040d279/starlark/src/environment/mod.rs#L34-L35

However, these are also exported by the common evaluation error codes:

https://github.com/google/starlark-rust/blob/094247066753b8d79c731f8c628e2934aada5555/starlark/src/eval/mod.rs#L82-L84

These error codes don't seem to line up either `RETURN_ERROR_CODE` != `CANNOT_IMPORT_ERROR_CODE` in my mind. Are these simple typo's or do they represent the exact same error case?

**Comment by damienmg** [comment]
Those are definitely error code clashes, that's why there is a TODO somewhere to have all error code in one place :)
