### ISSUE TITLE
scanner: scanner does not ignore an escaped carriage return

### ISSUE THREAD

**Issue by alandonovan** [google/starlark-rust#280]
(Re-reporting https://github.com/google/starlark-go/issues/144 here)

According to the original bug report, the scanner of Starlark/Rust treats an escaped carriage return (ASCII 13) as a two-char string, which is different from the scanners of Python and Starlark/Go, which ignore it. (Note: to type the expression below, interactively, you must type Ctrl-M where it says ^M.)

```
$ python -c 'print("""print(len("a\\\x0db"))""")' >a.star
$ cat -e a.star
print(len("a\^Mb"))$
$ python2 a.star
2
$ python3 a.star
2
$ go run go.starlark.net/cmd/starlark a.star
2
$ starlark-rust a.star
4
```
(I have not empirically validated the starlark-rust behavior; I am extrapolating from the original bug report.)

**Comment by illicitonion** [comment]
I reproduce that there _is_ a problem here, but the outcome I see is a error: `Unfinished string literal`, rather than a value of `4`. Regardless, fixed in #281 :)
