### ISSUE TITLE
support TERM=dumb or something like it

### ISSUE THREAD

**Issue by josharian** [google/starlark-rust#53]
I was hoping to get plain text output from `starlark-repl`, for when it is being invoked by another program (fuzz). This is what happens currently:

```
$ TERM=dumb starlark-repl -c "x" 
thread 'main' panicked at 'failed to emit error: operation not supported by the terminal', /Users/josh/.cargo/registry/src/github.com-1ecc6299db9ec823/codemap-diagnostic-0.1.0/src/emitter.rs:881:27
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by damienmg** [comment]
Oh yes this should be pretty simple to fix. We use `Always` for emitting color, we could use something dependent on the term instead.

**Comment by illicitonion** [comment]
Fired off https://github.com/kevinmehall/codemap-diagnostic/pull/5 so that codemap-diagnostic does the right thing for `TERM=dumb` and `ColorConfig::auto`.

If it doesn't get merged soon-ish we can either use a git dependency on the fork, or do something similar in our code.
